# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15dkWI8VQp2ODCJNFEGR3maL5kBNNi-EW
"""

!pip install streamlit

import streamlit as st
import pandas as pd

df = pd.read_csv("bls_data.csv")

st.title("BLS Labor Data Dashboard")

st.header("Latest Data")
latest_data = df[df['date'] == df['date'].max()]

st.write(latest_data)

st.header("Non-Farm Payrolls over Time")
non_farm_df = df[df['series_id'] == "CEU0000000001"]
st.line_chart(non_farm_df[['date', 'value']].set_index('date'))

st.header("Unemployment Rate over Time")
unemployment_df = df[df['series_id'] == "LNS14000000"]
st.line_chart(unemployment_df[['date', 'value']].set_index('date'))

st.header("Civilian Labor Force over Time")
civilian_df = df[df['series_id'] == "LNS11000000"]
st.line_chart(civilian_df[['date', 'value']].set_index('date'))